### ISSUE TITLE
planer breaks on html email with css link and jsdom 12

### ISSUE THREAD

**Issue by AdriVanHoudt** [lever/planer#10]
test case
```js
const Planer = require('planer');
const JSdom = require('jsdom');

const document = new JSdom.JSDOM().window.document;
Planer.extractFrom('<html><head><link rel="stylesheet" href="https://example.com/app.min.css"></head><body>hello world</body></html>', 'text/html', document);
```
live test case: https://runkit.com/adrivanhoudt/planer-jsdom-fetch-error

I think it has something to do with jsdom's new resource loader in v12.
Not sure why it is trying to load the resource though since it states it doesn't do that by default but maybe planer's use of innerHTML = body breaks it?

**Comment by l8on** [comment]
@AdriVanHoudt Thanks for the test case and runkit link.

At first blush, it seems like the issue is with `jsdom` in that it's loading sub-resources without being told to. According to their [npm page](https://www.npmjs.com/package/jsdom#basic-options) it shouldn't load resources by default, but it clearly is given your example.

It seems like one can configure a custom resource loader. Perhaps making a no-op `fetch` function on a custom resource loader would work around this problem. In any case, I will also experiment with jsdom@12 in the next few weeks to see if I can determine what about planer is not playing nice with their new fancy features.

**Comment by AdriVanHoudt** [comment]
@l8on I think you are right and I tried that with no luck but I think the `innerHTML = ` statement circumvents the loader thingy (being off) from the new jsdom version

**Comment by AdriVanHoudt** [comment]
This seems to be fixed in JSdom@14
